import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Quran V2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          E-Quran V2
        </h1>
        <p className={styles.description}>
          Powered by
          <code className={styles.code}><a href='https://chachanurholis.id'>Chacha Nurholis</a></code>
        </p>
      </main>
    </div>
  )
}
